---
# This file is part of Ansible role geoffreyvanwyk.moodle.
#
# Ansible role geoffreyvanwyk.moodle is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible role geoffreyvanwyk.moodle is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.moodle. If not, see
# <https://www.gnu.org/licenses/>.

##
# Install the specified database service and create the required database with
# associated user.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Ensure APT keyrings directory exists
  # The /etc/apt/keyrings directory does not exist on Ubuntu 20.04
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Database Service - PostgreSQL
  # See https://www.postgresql.org/docs/14/app-initdb.html
  when: moodle_cfg_dbtype == 'pgsql'
  vars:
    moodle_postgresql_version: 14
    moodle_postgresql_bin: >-
      /usr/lib/postgresql/{{ moodle_postgresql_version }}/bin
    moodle_postgresql_lib: >-
      /var/lib/postgresql/{{ moodle_postgresql_version }}/main
  block:
    - name: Download signing key for PostgreSQL APT package repository
      become: true
      ansible.builtin.uri:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        status_code:
          - 200
          - 304
        dest: /etc/apt/keyrings/postgresql.asc
        creates: /etc/apt/keyrings/postgresql.asc

    - name: Add APT package repository for PostgreSQL
      become: true
      ansible.builtin.apt_repository:
        repo: >-
          deb
          [arch=amd64 signed-by=/etc/apt/keyrings/postgresql.asc]
          http://apt.postgresql.org/pub/repos/apt
          {{ ansible_distribution_release }}-pgdg main
        state: present

    - name: Install PostgreSQL
      become: true
      ansible.builtin.apt:
        package:
          - postgresql-{{ moodle_postgresql_version }}
          - postgresql-contrib-{{ moodle_postgresql_version }}
          - libpq-dev # Necessary for postgresql_* modules
          - python3-psycopg2 # Necessary for postgresql_* modules
          - acl # Necessary for initializing PostgreSQL
        state: present

    - name: Start PostgreSQL service
      become: true
      ansible.builtin.sysvinit:
        name: postgresql
        state: started
        enabled: true

    - name: Create database user
      become: true
      become_user: postgres
      block:
        - name: Check if PostgreSQL role exists
          ansible.builtin.command:
            cmd: 'psql -tAc "SELECT 1 FROM pg_roles WHERE rolname=''{{ moodle_cfg_dbuser }}''"'
          register: secure_moodle_pg_role_exists
          changed_when: false

        - name: Create PostgreSQL role (if missing)
          when: secure_moodle_pg_role_exists.stdout.strip() != '1'
          ansible.builtin.command:
            cmd: 'psql -c "CREATE USER {{ moodle_cfg_dbuser }} WITH PASSWORD ''{{ moodle_cfg_dbpass }}'';"'
          changed_when: true

    - name: Create database
      become: true
      become_user: postgres
      block:
        - name: Check if PostgreSQL database exists
          ansible.builtin.command:
            cmd: 'psql -tAc "SELECT 1 FROM pg_database WHERE datname=''{{ moodle_cfg_dbname }}''"'
          register: secure_moodle_pg_db_exists
          changed_when: false

        - name: Create PostgreSQL database (if missing)
          when: secure_moodle_pg_db_exists.stdout.strip() != '1'
          ansible.builtin.command:
            cmd: "createdb -O {{ moodle_cfg_dbuser }} {{ moodle_cfg_dbname }}"
          changed_when: true

- name: Database Service - MariaDB
  # See http://tinyurl.com/mariadb-10-6-download
  when: moodle_cfg_dbtype == 'mariadb'
  vars:
    moodle_mariadb_version: 10.6
  block:
    - name: Download signing key for MariaDB APT package repository
      become: true
      ansible.builtin.uri:
        url: https://mariadb.org/mariadb_release_signing_key.pgp
        status_code:
          - 200
          - 304
        dest: /etc/apt/keyrings/mariadb-keyring.pgp
        creates: /etc/apt/keyrings/mariadb-keyring.pgp

    # yamllint disable rule:line-length
    - name: Add APT package repository for MariaDB
      become: true
      ansible.builtin.apt_repository:
        repo: >-
          deb
          [signed-by=/etc/apt/keyrings/mariadb-keyring.pgp]
          https://mariadb.mirror.liquidtelecom.com/repo/{{ moodle_mariadb_version }}/ubuntu
          {{ ansible_distribution_release }}
          main
        state: present
    # yamllint enable rule:line-length

    - name: Install MariaDB
      become: true
      ansible.builtin.apt:
        package:
          - mariadb-server
          - python3-pymysql # Needed for mysql_* modules
        state: present

    - name: Start MariaDB service
      become: true
      ansible.builtin.sysvinit:
        name: mariadb
        state: started
        enabled: true

    - name: Create MariaDB database (idempotent)
      become: true
      ansible.builtin.command:
        argv:
          - mysql
          - --protocol=socket
          - --socket=/run/mysqld/mysqld.sock
          - -e
          - "CREATE DATABASE IF NOT EXISTS `{{ moodle_cfg_dbname }}`;"
      changed_when: false

    # yamllint disable rule:line-length
    - name: Create MariaDB user (idempotent)
      become: true
      ansible.builtin.command:
        argv:
          - mysql
          - --protocol=socket
          - --socket=/run/mysqld/mysqld.sock
          - -e
          - >-
            CREATE USER IF NOT EXISTS '{{ moodle_cfg_dbuser }}'@'localhost'
            IDENTIFIED BY '{{ moodle_cfg_dbpass }}';
      changed_when: false

    - name: Grant MariaDB privileges (idempotent)
      become: true
      ansible.builtin.command:
        argv:
          - mysql
          - --protocol=socket
          - --socket=/run/mysqld/mysqld.sock
          - -e
          - >-
            GRANT ALL PRIVILEGES ON `{{ moodle_cfg_dbname }}`.* TO
            '{{ moodle_cfg_dbuser }}'@'localhost'; FLUSH PRIVILEGES;
      changed_when: false
    # yamllint enable rule:line-length
